steps:
    - name: node
      entrypoint: npm
      args: ['install']   
    - name: node
      entrypoint: npm
      args: ['run']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/[PROJECT_ID]/[IMAGE_NAME]', '.']
      
