steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'nodebackend-run', '--image', 'gcr.io/nodebackend/nodebackend-run:${SHORT_SHA}', '--region', 'us-central1', '--allow-unauthenticated']  
images:
- gcr.io/nodebackend/nodebackend-run
